---
aliases: [save-load.html]
---

# Serialisation

{{< include _setup.qmd >}}

## XDR encoding

```{r}
#| results: asis
#| echo: false
render_entries("serialisation", "XDR encoding")
```

## Persistence streams

```c
typedef void *R_pstream_data_t;

typedef enum {
  R_pstream_any_format,
  R_pstream_ascii_format,
  R_pstream_binary_format,
  R_pstream_xdr_format,
  R_pstream_asciihex_format
} R_pstream_format_t;

typedef struct R_outpstream_st *R_outpstream_t;
struct R_outpstream_st {
  R_pstream_data_t data;
  R_pstream_format_t type;
  int version;
  void (*OutChar)(R_outpstream_t, int);
  void (*OutBytes)(R_outpstream_t, void *, int);
  SEXP (*OutPersistHookFunc)(SEXP, SEXP);
  SEXP OutPersistHookData;
};

typedef struct R_inpstream_st *R_inpstream_t;
struct R_inpstream_st {
  R_pstream_data_t data;
  R_pstream_format_t type;
  int (*InChar)(R_inpstream_t);
  void (*InBytes)(R_inpstream_t, void *, int);
  SEXP (*InPersistHookFunc)(SEXP, SEXP);
  SEXP InPersistHookData;
};
```

```{r}
#| results: asis
#| echo: false
render_entries("serialisation", "Persistence streams")
```

The connection interface is not available to packages. To allow limited use of connection pointers, defining `NEED_CONNECTION_PSTREAMS` before including `Rinternals.h` defines the opaque pointer type:

```c
#ifdef NEED_CONNECTION_PSTREAMS
#ifndef HAVE_RCONNECTION_TYPEDEF
typedef struct Rconn  *Rconnection;
#define HAVE_RCONNECTION_TYPEDEF
#endif
#endif
```

## Serialising objects

```{r}
#| results: asis
#| echo: false
render_entries("serialisation", "Serialising objects")
```
